engines:
  eslint:
    enabled: true
    checks:
      import/extensions:
        enabled: false
  duplication:
    enabled: false
    config:
      languages:
      - javascript
ratings:
  paths:
  - "**.js"
exclude_paths:
- tests
- client/public
